<html>

<head>
</head>

<body >

<div style="size:8.5in 11.0in;margin:.5in .5in .5in .5in;">

<table class=MsoTableGrid border=1 cellspacing=0 cellpadding=0
 style='border-collapse:collapse;border:none'>
 <tr style='height:.3in'>
  <td width=149 valign=top style='width:149.4pt;border:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:.3in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><b>Date: </b><b>$date$</b></p>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;">&nbsp;</p>
  </td>
  <td width=218 colspan=4 valign=top style='width:217.8pt;border:solid windowtext 1.0pt;
  border-left:none;padding:0in 5.4pt 0in 5.4pt;height:.3in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><b>Producer: </b><b><span>$producerName$</span></b></p>
  </td>
  <td width=184 colspan=3 valign=top style='width:2.55in;border:solid windowtext 1.0pt;
  border-left:none;padding:0in 5.4pt 0in 5.4pt;height:.3in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><b>Branch: </b><b><span>$branch$</span></b></p>
  </td>
 </tr>
 <tr style='height:.3in'>
  <td width=149 valign=top style='width:149.4pt;border:solid windowtext 1.0pt;
  border-top:none;padding:0in 5.4pt 0in 5.4pt;height:.3in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><b>Key Contact: </b><b><span></span></b></p>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;">$keyContact$</p>
  </td>
  <td width=218 colspan=4 valign=top style='width:217.8pt;border-top:none;
  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:.3in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><b>Phone (s): </b><b><span>$keyPhone$</span></b></p>
  </td>
  <td width=184 colspan=3 valign=top style='width:2.55in;border-top:none;
  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:.3in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><b>Email: </b><b><span>$keyEmail$</span></b></p>
  </td>
 </tr>
 <tr style='height:.3in'>
  <td width=149 valign=top style='width:149.4pt;border:solid windowtext 1.0pt;
  border-top:none;padding:0in 5.4pt 0in 5.4pt;height:.3in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><b>Secondary Contact: </b><b><span></span></b></p>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><b>$secondaryContact$</b></p>
  </td>
  <td width=218 colspan=4 valign=top style='width:217.8pt;border-top:none;
  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:.3in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><b>Phone (s): </b><b><span>$secondaryPhone$</span></b></p>
  </td>
  <td width=184 colspan=3 valign=top style='width:2.55in;border-top:none;
  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:.3in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><b>Email: </b><b><span>$secondaryEmail$</span></b></p>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;">&nbsp;</p>
  </td>
 </tr>
 <tr style='height:.3in'>
  <td width=149 rowspan=3 valign=top style='width:149.4pt;border:solid windowtext 1.0pt;
  border-top:none;padding:0in 5.4pt 0in 5.4pt;height:.3in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><b>Business Name(s):</b></p>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;">$businessType$</p>

  </td>
  <td width=401 colspan=7 valign=top style='width:401.4pt;border-top:none;
  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:.3in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><b>$businessName$</b></p>
  </td>
 </tr>
 <tr style='height:.2in'>
  <td width=401 colspan=7 valign=top style='width:401.4pt;border-top:none;
  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:.2in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><b><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></b></p>
  </td>
 </tr>
 <tr style='height:13.7pt'>
  <td width=401 colspan=7 valign=top style='width:401.4pt;border-top:none;
  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:13.7pt'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><b><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></b></p>
  </td>
 </tr>
 <tr style='height:27.35pt'>
  <td width=149 rowspan=3 valign=top style='width:149.4pt;border:solid windowtext 1.0pt;
  border-top:none;padding:0in 5.4pt 0in 5.4pt;height:27.35pt'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><b>Mailing Address:</b></p>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><b>&nbsp;</b></p>
  </td>
  <td width=218 colspan=4 rowspan=2 valign=top style='width:217.8pt;border-top:
  none;border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:27.35pt'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><b><span>$mailingAddress$</span></b></p>
  </td>
  <td width=184 colspan=3 valign=top style='width:2.55in;border-top:none;
  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:27.35pt'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><b>Fax #:  </b><b><span>$fax$</span></b></p>
  </td>
 </tr>
 <tr style='height:27.35pt'>
  <td width=184 colspan=3 valign=top style='width:2.55in;border-top:none;
  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:27.35pt'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><b>Website: </b><b><span>$website$</span></b></p>
  </td>
 </tr>
 <tr>
  <td width=153 colspan=2 valign=top style='width:153.0pt;border-top:none;
  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><b># of Locations:  </b><b><span>$nooflocations$</span></b></p>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;">&nbsp;</p>
  </td>
  <td width=248 colspan=5 valign=top style='width:3.45in;border-top:none;
  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><b># of Owned Autos: </b><b><span>$noofownedautos$</span></b></p>
  </td>
 </tr>
 <tr style='height:.4in'>
  <td width=149 valign=top style='width:149.4pt;border:solid windowtext 1.0pt;
  border-top:none;padding:0in 5.4pt 0in 5.4pt;height:.4in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><b>Entity Type:</b></p>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><span style='font-size:9.0pt'>(Corporation, Sole Proprietor, Other)</span></p>
  </td>
  <td width=153 colspan=2 valign=top style='width:153.0pt;border-top:none;
  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:.4in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><b><span>$entityType$</span></b></p>
  </td>
  <td width=104 colspan=3 valign=top style='width:103.5pt;border-top:none;
  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:.4in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><b>For Profit/Non Profit:</b></p>
  </td>
  <td width=145 colspan=2 valign=top style='width:144.9pt;border-top:none;
  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:.4in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><b><span>$profitornonprofit$</span></b></p>
  </td>
 </tr>
 <tr style='height:.7in'>
  <td width=149 valign=top style='width:149.4pt;border:solid windowtext 1.0pt;
  border-top:none;padding:0in 5.4pt 0in 5.4pt;height:.7in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><b>Years in Business:</b></p>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><b>&nbsp;</b></p>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;" align=center style='margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal'><b><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></b></p>
  </td>
  <td width=401 colspan=7 valign=top style='width:401.4pt;border-top:none;
  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:.7in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><b>Related Experience: </b><b><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></b></p>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;">&nbsp;</p>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;">&nbsp;</p>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;">&nbsp;</p>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;">&nbsp;</p>
  </td>
 </tr>
 <tr style='height:13.7pt'>
  <td width=149 rowspan=5 valign=top style='width:149.4pt;border:solid windowtext 1.0pt;
  border-top:none;padding:0in 5.4pt 0in 5.4pt;height:13.7pt'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><b>Owner(s) &amp; Key Personnel:</b></p>
  </td>
  <td width=401 colspan=7 valign=top style='width:401.4pt;border-top:none;
  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:13.7pt'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><b><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></b></p>
  </td>
 </tr>
 <tr style='height:13.7pt'>
  <td width=401 colspan=7 valign=top style='width:401.4pt;border-top:none;
  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:13.7pt'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><b><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></b></p>
  </td>
 </tr>
 <tr style='height:13.7pt'>
  <td width=401 colspan=7 valign=top style='width:401.4pt;border-top:none;
  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:13.7pt'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><b><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></b></p>
  </td>
 </tr>
 <tr style='height:13.7pt'>
  <td width=401 colspan=7 valign=top style='width:401.4pt;border-top:none;
  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:13.7pt'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><b><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></b></p>
  </td>
 </tr>
 <tr style='height:13.7pt'>
  <td width=401 colspan=7 valign=top style='width:401.4pt;border-top:none;
  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:13.7pt'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><b><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></b></p>
  </td>
 </tr>
 <tr style='height:13.7pt'>
  <td width=149 rowspan=4 valign=top style='width:149.4pt;border:solid windowtext 1.0pt;
  border-top:none;padding:0in 5.4pt 0in 5.4pt;height:13.7pt'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><b>Board of Directors:</b></p>
  </td>
  <td width=401 colspan=7 valign=top style='width:401.4pt;border-top:none;
  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:13.7pt'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><b><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></b></p>
  </td>
 </tr>
 <tr style='height:13.7pt'>
  <td width=401 colspan=7 valign=top style='width:401.4pt;border-top:none;
  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:13.7pt'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><b><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></b></p>
  </td>
 </tr>
 <tr style='height:13.7pt'>
  <td width=401 colspan=7 valign=top style='width:401.4pt;border-top:none;
  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:13.7pt'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><b><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></b></p>
  </td>
 </tr>
 <tr style='height:13.5pt'>
  <td width=401 colspan=7 valign=top style='width:401.4pt;border-top:none;
  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:13.5pt'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><b><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></b></p>
  </td>
 </tr>
 <tr style='height:.2in'>
  <td width=149 rowspan=2 valign=top style='width:149.4pt;border:solid windowtext 1.0pt;
  border-top:none;padding:0in 5.4pt 0in 5.4pt;height:.2in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><b>Financial Year End:</b></p>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><b><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></b></p>
  </td>
  <td width=100 rowspan=2 valign=top style='width:100.35pt;border-top:none;
  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:.2in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><b># of Staff: </b><b><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></b></p>
  </td>
  <td width=100 colspan=2 rowspan=2 valign=top style='width:100.35pt;
  border-top:none;border-left:none;border-bottom:solid windowtext 1.0pt;
  border-right:solid windowtext 1.0pt;padding:0in 5.4pt 0in 5.4pt;height:.2in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><b>Payroll$:</b><b><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></b></p>
  </td>
  <td width=100 colspan=3 valign=top style='width:100.35pt;border-top:none;
  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:.2in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><b>Grp. &nbsp;Benefits Y/N:</b></p>
  </td>
  <td width=100 valign=top style='width:100.35pt;border-top:none;border-left:
  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:.2in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><b><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></b></p>
  </td>
 </tr>
 <tr style='height:13.7pt'>
  <td width=100 colspan=3 valign=top style='width:100.35pt;border-top:none;
  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:13.7pt'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><b>Pension Plan Y/N:</b></p>
  </td>
  <td width=100 valign=top style='width:100.35pt;border-top:none;border-left:
  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:13.7pt'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><b><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></b></p>
  </td>
 </tr>
 <tr style='height:20.15pt'>
  <td width=149 rowspan=7 valign=top style='width:149.4pt;border:solid windowtext 1.0pt;
  border-top:none;padding:0in 5.4pt 0in 5.4pt;height:20.15pt'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><b>Description of Operations and Revenues: </b><b><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></b></p>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;">&nbsp;</p>
  </td>
  <td width=201 colspan=3 valign=top style='width:200.7pt;border-top:none;
  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:20.15pt'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;">1)<b> </b><b><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></b></p>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;">&nbsp;</p>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;">&nbsp;</p>
  </td>
  <td width=201 colspan=4 valign=top style='width:200.7pt;border-top:none;
  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:20.15pt'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;">4)<b> </b><b><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></b></p>
  </td>
 </tr>
 <tr style='height:20.15pt'>
  <td width=100 valign=top style='width:100.35pt;border-top:none;border-left:
  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:20.15pt'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;">$<b><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></b></p>
  </td>
  <td width=100 colspan=2 valign=top style='width:100.35pt;border-top:none;
  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:20.15pt'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;">US$<b><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></b></p>
  </td>
  <td width=100 colspan=3 valign=top style='width:100.35pt;border-top:none;
  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:20.15pt'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;">$<b><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></b></p>
  </td>
  <td width=100 valign=top style='width:100.35pt;border-top:none;border-left:
  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:20.15pt'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;">US$<b><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></b></p>
  </td>
 </tr>
 <tr style='page-break-inside:avoid;height:20.15pt'>
  <td width=201 colspan=3 valign=top style='width:200.7pt;border-top:none;
  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:20.15pt'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;">2)<b> </b><b><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></b></p>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;">&nbsp;</p>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;">&nbsp;</p>
  </td>
  <td width=201 colspan=4 valign=top style='width:200.7pt;border-top:none;
  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:20.15pt'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;">5)<b> </b><b><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></b></p>
  </td>
 </tr>
 <tr style='height:20.15pt'>
  <td width=100 valign=top style='width:100.35pt;border-top:none;border-left:
  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:20.15pt'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;">$<b><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></b></p>
  </td>
  <td width=100 colspan=2 valign=top style='width:100.35pt;border-top:none;
  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:20.15pt'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;">US$<b><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></b></p>
  </td>
  <td width=100 colspan=3 valign=top style='width:100.35pt;border-top:none;
  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:20.15pt'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;">$<b><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></b></p>
  </td>
  <td width=100 valign=top style='width:100.35pt;border-top:none;border-left:
  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:20.15pt'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;">$US<b><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></b></p>
  </td>
 </tr>
 <tr style='page-break-inside:avoid;height:20.15pt'>
  <td width=201 colspan=3 valign=top style='width:200.7pt;border-top:none;
  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:20.15pt'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;">3)<b> </b><b><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></b></p>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;">&nbsp;</p>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;">&nbsp;</p>
  </td>
  <td width=201 colspan=4 valign=top style='width:200.7pt;border-top:none;
  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:20.15pt'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;">6)<b> </b><b><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></b></p>
  </td>
 </tr>
 <tr style='height:20.15pt'>
  <td width=100 valign=top style='width:100.35pt;border-top:none;border-left:
  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:20.15pt'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;">$<b><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></b></p>
  </td>
  <td width=100 colspan=2 valign=top style='width:100.35pt;border-top:none;
  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:20.15pt'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;">US$<b><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></b></p>
  </td>
  <td width=100 colspan=3 valign=top style='width:100.35pt;border-top:none;
  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:20.15pt'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;">$<b><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></b></p>
  </td>
  <td width=100 valign=top style='width:100.35pt;border-top:none;border-left:
  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:20.15pt'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;">$US<b><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></b></p>
  </td>
 </tr>
 <tr style='height:.2in'>
  <td width=201 colspan=3 valign=top style='width:200.7pt;border-top:none;
  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:.2in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><b>Total Sales:$ </b><b><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></b></p>
  </td>
  <td width=201 colspan=4 valign=top style='width:200.7pt;border-top:none;
  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:.2in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><b>% of US Sales</b><b><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></b></p>
  </td>
 </tr>
 <tr height=0>
  <td width=149 style='border:none'></td>
  <td width=100 style='border:none'></td>
  <td width=53 style='border:none'></td>
  <td width=48 style='border:none'></td>
  <td width=17 style='border:none'></td>
  <td width=39 style='border:none'></td>
  <td width=45 style='border:none'></td>
  <td width=100 style='border:none'></td>
 </tr>
</table>

<p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;">&nbsp;</p>

<table class=MsoTableGrid border=1 cellspacing=0 cellpadding=0
 style='border-collapse:collapse;border:none'>
 <tr style='height:.3in'>
  <td width=184 colspan=2 rowspan=3 valign=top style='width:2.55in;border:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:.3in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><b>Largest Customers or Projects:</b></p>
  </td>
  <td width=184 colspan=2 valign=top style='width:2.55in;border:solid windowtext 1.0pt;
  border-left:none;padding:0in 5.4pt 0in 5.4pt;height:.3in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;">1)<b> </b><b><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></b></p>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;">&nbsp;</p>
  </td>
  <td width=184 colspan=4 valign=top style='width:2.55in;border:solid windowtext 1.0pt;
  border-left:none;padding:0in 5.4pt 0in 5.4pt;height:.3in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;">4)<b> </b><b><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></b></p>
  </td>
 </tr>
 <tr style='height:.3in'>
  <td width=184 colspan=2 valign=top style='width:2.55in;border-top:none;
  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:.3in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;">2)<b> </b><b><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></b></p>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;">&nbsp;</p>
  </td>
  <td width=184 colspan=4 valign=top style='width:2.55in;border-top:none;
  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:.3in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;">5)<b> </b><b><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></b></p>
  </td>
 </tr>
 <tr style='page-break-inside:avoid;height:.3in'>
  <td width=184 colspan=2 valign=top style='width:2.55in;border-top:none;
  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:.3in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;">3)<b> </b><b><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></b></p>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;">&nbsp;</p>
  </td>
  <td width=184 colspan=4 valign=top style='width:2.55in;border-top:none;
  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:.3in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;">6)<b> </b><b><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></b></p>
  </td>
 </tr>
 <tr style='page-break-inside:avoid;height:.3in'>
  <td width=184 colspan=2 rowspan=2 valign=top style='width:2.55in;border:solid windowtext 1.0pt;
  border-top:none;padding:0in 5.4pt 0in 5.4pt;height:.3in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><b>Largest Suppliers:</b></p>
  </td>
  <td width=184 colspan=2 valign=top style='width:2.55in;border-top:none;
  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:.3in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;">1)<b> </b><b><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></b></p>
  </td>
  <td width=184 colspan=4 valign=top style='width:2.55in;border-top:none;
  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:.3in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;">3)<b> </b><b><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></b></p>
  </td>
 </tr>
 <tr style='height:.3in'>
  <td width=184 colspan=2 valign=top style='width:2.55in;border-top:none;
  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:.3in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;">2)<b> </b><b><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></b></p>
  </td>
  <td width=184 colspan=4 valign=top style='width:2.55in;border-top:none;
  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:.3in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;">4)<b> </b><b><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></b></p>
  </td>
 </tr>
 <tr style='height:38.9pt'>
  <td width=184 colspan=2 valign=top style='width:2.55in;border:solid windowtext 1.0pt;
  border-top:none;padding:0in 5.4pt 0in 5.4pt;height:38.9pt'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><b>Future Opportunities or Plans for Growth:</b></p>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><b></b>Bonding Opportunities?</p>
  </td>
  <td width=367 colspan=6 valign=top style='width:5.1in;border-top:none;
  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:38.9pt'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;">&nbsp;</p>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><b><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></b></p>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;">&nbsp;</p>
  </td>
 </tr>
 <tr style='height:.5in'>
  <td width=184 colspan=2 valign=top style='width:2.55in;border:solid windowtext 1.0pt;
  border-top:none;padding:0in 5.4pt 0in 5.4pt;height:.5in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><b>Describe Competition:</b></p>
  </td>
  <td width=367 colspan=6 valign=top style='width:5.1in;border-top:none;
  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:.5in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;">&nbsp;</p>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><b><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></b></p>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;">&nbsp;</p>
  </td>
 </tr>
 <tr style='height:.5in'>
  <td width=184 colspan=2 valign=top style='width:2.55in;border:solid windowtext 1.0pt;
  border-top:none;padding:0in 5.4pt 0in 5.4pt;height:.5in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><b>What Sets Your Business Apart From the Competition?:</b></p>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;">&nbsp;</p>
  </td>
  <td width=367 colspan=6 valign=top style='width:5.1in;border-top:none;
  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:.5in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><b><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></b></p>
  </td>
 </tr>
 <tr style='height:.5in'>
  <td width=184 colspan=2 valign=top style='width:2.55in;border:solid windowtext 1.0pt;
  border-top:none;padding:0in 5.4pt 0in 5.4pt;height:.5in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><b>Describe Any Advertising:</b></p>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;">&nbsp;</p>
  </td>
  <td width=367 colspan=6 valign=top style='width:5.1in;border-top:none;
  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:.5in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><b><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></b></p>
  </td>
 </tr>
 <tr style='height:.7in'>
  <td width=184 colspan=2 valign=top style='width:2.55in;border:solid windowtext 1.0pt;
  border-top:none;padding:0in 5.4pt 0in 5.4pt;height:.7in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><b>How Long Would it Take to Recover From a Serious Claim?:</b></p>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><b></b>Business Interruption Worksheet?</p>
  </td>
  <td width=367 colspan=6 valign=top style='width:5.1in;border-top:none;
  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:.7in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><b><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></b></p>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;">&nbsp;</p>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;">&nbsp;</p>
  </td>
 </tr>
 <tr style='height:.15in'>
  <td width=184 colspan=2 rowspan=5 valign=top style='width:2.55in;border:solid windowtext 1.0pt;
  border-top:none;padding:0in 5.4pt 0in 5.4pt;height:.15in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><b>Details of Past or Potential Claims (5yrs):</b></p>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><span style='font-size:9.0pt'>(Include Date, Cause &amp; $ Amount)</span></p>
  </td>
  <td width=367 colspan=6 valign=top style='width:5.1in;border-top:none;
  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:.15in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><b><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></b></p>
  </td>
 </tr>
 <tr style='height:.15in'>
  <td width=367 colspan=6 valign=top style='width:5.1in;border-top:none;
  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:.15in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><b><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></b></p>
  </td>
 </tr>
 <tr style='height:.15in'>
  <td width=367 colspan=6 valign=top style='width:5.1in;border-top:none;
  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:.15in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><b><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></b></p>
  </td>
 </tr>
 <tr style='height:.15in'>
  <td width=367 colspan=6 valign=top style='width:5.1in;border-top:none;
  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:.15in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><b><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></b></p>
  </td>
 </tr>
 <tr style='height:.15in'>
  <td width=367 colspan=6 valign=top style='width:5.1in;border-top:none;
  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:.15in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><b><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></b></p>
  </td>
 </tr>
 <tr style='height:.2in'>
  <td width=184 colspan=2 rowspan=5 valign=top style='width:2.55in;border:solid windowtext 1.0pt;
  border-top:none;padding:0in 5.4pt 0in 5.4pt;height:.2in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><b>Schedule of Current Insurance Policies: </b><b><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></b></p>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><span style='font-size:9.0pt'>&nbsp;</span></p>
  </td>
  <td width=122 valign=top style='width:1.7in;border-top:none;border-left:none;
  border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:.2in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;" align=center style='margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal'>Type</p>
  </td>
  <td width=122 colspan=3 valign=top style='width:1.7in;border-top:none;
  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:.2in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;" align=center style='margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal'>Carrier</p>
  </td>
  <td width=122 colspan=2 valign=top style='width:1.7in;border-top:none;
  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:.2in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;" align=center style='margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal'>Expiry</p>
  </td>
 </tr>
 <tr style='height:.2in'>
  <td width=122 valign=top style='width:1.7in;border-top:none;border-left:none;
  border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:.2in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><b><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></b></p>
  </td>
  <td width=122 colspan=3 valign=top style='width:1.7in;border-top:none;
  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:.2in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><b><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></b></p>
  </td>
  <td width=122 colspan=2 valign=top style='width:1.7in;border-top:none;
  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:.2in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><b><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></b></p>
  </td>
 </tr>
 <tr style='height:.2in'>
  <td width=122 valign=top style='width:1.7in;border-top:none;border-left:none;
  border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:.2in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><b><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></b></p>
  </td>
  <td width=122 colspan=3 valign=top style='width:1.7in;border-top:none;
  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:.2in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><b><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></b></p>
  </td>
  <td width=122 colspan=2 valign=top style='width:1.7in;border-top:none;
  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:.2in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><b><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></b></p>
  </td>
 </tr>
 <tr style='height:.2in'>
  <td width=122 valign=top style='width:1.7in;border-top:none;border-left:none;
  border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:.2in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><b><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></b></p>
  </td>
  <td width=122 colspan=3 valign=top style='width:1.7in;border-top:none;
  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:.2in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><b><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></b></p>
  </td>
  <td width=122 colspan=2 valign=top style='width:1.7in;border-top:none;
  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:.2in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><b><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></b></p>
  </td>
 </tr>
 <tr style='height:.2in'>
  <td width=122 valign=top style='width:1.7in;border-top:none;border-left:none;
  border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:.2in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><b><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></b></p>
  </td>
  <td width=122 colspan=3 valign=top style='width:1.7in;border-top:none;
  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:.2in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><b><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></b></p>
  </td>
  <td width=122 colspan=2 valign=top style='width:1.7in;border-top:none;
  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:.2in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><b><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></b></p>
  </td>
 </tr>
 <tr style='height:.2in'>
  <td width=184 colspan=2 rowspan=4 valign=top style='width:2.55in;border:solid windowtext 1.0pt;
  border-top:none;padding:0in 5.4pt 0in 5.4pt;height:.2in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><b>Lienholders: </b><b><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></b></p>
  </td>
  <td width=184 colspan=2 valign=top style='width:2.55in;border-top:none;
  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:.2in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><b><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></b></p>
  </td>
  <td width=184 colspan=4 valign=top style='width:2.55in;border-top:none;
  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:.2in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;">Loc#:<b><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></b></p>
  </td>
 </tr>
 <tr style='height:.2in'>
  <td width=184 colspan=2 valign=top style='width:2.55in;border-top:none;
  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:.2in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><b><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></b></p>
  </td>
  <td width=184 colspan=4 valign=top style='width:2.55in;border-top:none;
  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:.2in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;">Loc#:<b><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></b></p>
  </td>
 </tr>
 <tr style='height:.2in'>
  <td width=184 colspan=2 valign=top style='width:2.55in;border-top:none;
  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:.2in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><b><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></b></p>
  </td>
  <td width=184 colspan=4 valign=top style='width:2.55in;border-top:none;
  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:.2in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;">Loc#:<b><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></b></p>
  </td>
 </tr>
 <tr style='height:.2in'>
  <td width=184 colspan=2 valign=top style='width:2.55in;border-top:none;
  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:.2in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><b><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></b></p>
  </td>
  <td width=184 colspan=4 valign=top style='width:2.55in;border-top:none;
  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:.2in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;">Loc#:<b><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></b></p>
  </td>
 </tr>
 <tr style='height:.2in'>
  <td width=140 rowspan=6 valign=top style='width:1.95in;border:solid windowtext 1.0pt;
  border-top:none;padding:0in 5.4pt 0in 5.4pt;height:.2in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><b>Addresses of Locations:</b></p>
  </td>
  <td width=43 valign=top style='width:.6in;border-top:none;border-left:none;
  border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:.2in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;" align=center style='margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal'>#</p>
  </td>
  <td width=204 colspan=3 valign=top style='width:204.3pt;border-top:none;
  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:.2in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;" align=center style='margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal'>Address</p>
  </td>
  <td width=95 colspan=2 valign=top style='width:94.95pt;border-top:none;
  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:.2in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;" align=center style='margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal'>Use</p>
  </td>
  <td width=68 valign=top style='width:67.95pt;border-top:none;border-left:
  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:.2in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;" align=center style='margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal'>Owned Y/N</p>
  </td>
 </tr>
 <tr style='height:.2in'>
  <td width=43 valign=top style='width:.6in;border-top:none;border-left:none;
  border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:.2in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;" align=center style='margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal'>1</p>
  </td>
  <td width=204 colspan=3 valign=top style='width:204.3pt;border-top:none;
  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:.2in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><b><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></b></p>
  </td>
  <td width=95 colspan=2 valign=top style='width:94.95pt;border-top:none;
  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:.2in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><b><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></b></p>
  </td>
  <td width=68 valign=top style='width:67.95pt;border-top:none;border-left:
  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:.2in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><b><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></b></p>
  </td>
 </tr>
 <tr style='height:.2in'>
  <td width=43 valign=top style='width:.6in;border-top:none;border-left:none;
  border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:.2in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;" align=center style='margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal'>2</p>
  </td>
  <td width=204 colspan=3 valign=top style='width:204.3pt;border-top:none;
  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:.2in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><b><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></b></p>
  </td>
  <td width=95 colspan=2 valign=top style='width:94.95pt;border-top:none;
  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:.2in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><b><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></b></p>
  </td>
  <td width=68 valign=top style='width:67.95pt;border-top:none;border-left:
  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:.2in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><b><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></b></p>
  </td>
 </tr>
 <tr style='height:.2in'>
  <td width=43 valign=top style='width:.6in;border-top:none;border-left:none;
  border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:.2in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;" align=center style='margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal'>3</p>
  </td>
  <td width=204 colspan=3 valign=top style='width:204.3pt;border-top:none;
  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:.2in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><b><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></b></p>
  </td>
  <td width=95 colspan=2 valign=top style='width:94.95pt;border-top:none;
  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:.2in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><b><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></b></p>
  </td>
  <td width=68 valign=top style='width:67.95pt;border-top:none;border-left:
  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:.2in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><b><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></b></p>
  </td>
 </tr>
 <tr style='height:.2in'>
  <td width=43 valign=top style='width:.6in;border-top:none;border-left:none;
  border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:.2in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;" align=center style='margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal'>4</p>
  </td>
  <td width=204 colspan=3 valign=top style='width:204.3pt;border-top:none;
  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:.2in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><b><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></b></p>
  </td>
  <td width=95 colspan=2 valign=top style='width:94.95pt;border-top:none;
  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:.2in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><b><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></b></p>
  </td>
  <td width=68 valign=top style='width:67.95pt;border-top:none;border-left:
  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:.2in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><b><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></b></p>
  </td>
 </tr>
 <tr style='height:.2in'>
  <td width=43 valign=top style='width:.6in;border-top:none;border-left:none;
  border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:.2in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;" align=center style='margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal'>5</p>
  </td>
  <td width=204 colspan=3 valign=top style='width:204.3pt;border-top:none;
  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:.2in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><b><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></b></p>
  </td>
  <td width=95 colspan=2 valign=top style='width:94.95pt;border-top:none;
  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:.2in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><b><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></b></p>
  </td>
  <td width=68 valign=top style='width:67.95pt;border-top:none;border-left:
  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:.2in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><b><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></b></p>
  </td>
 </tr>
 <tr style='height:.2in'>
  <td width=140 rowspan=5 valign=top style='width:1.95in;border:solid windowtext 1.0pt;
  border-top:none;padding:0in 5.4pt 0in 5.4pt;height:.2in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><b>Locations Rented to Others:</b></p>
  </td>
  <td width=43 valign=top style='width:.6in;border-top:none;border-left:none;
  border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:.2in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;" align=center style='margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal'>1</p>
  </td>
  <td width=367 colspan=6 valign=top style='width:5.1in;border-top:none;
  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:.2in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;">Occupancy:<b> </b><b><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></b></p>
  </td>
 </tr>
 <tr style='height:.2in'>
  <td width=43 valign=top style='width:.6in;border-top:none;border-left:none;
  border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:.2in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;" align=center style='margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal'>2</p>
  </td>
  <td width=367 colspan=6 valign=top style='width:5.1in;border-top:none;
  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:.2in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;">Occupancy:<b> </b><b><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></b></p>
  </td>
 </tr>
 <tr style='height:.2in'>
  <td width=43 valign=top style='width:.6in;border-top:none;border-left:none;
  border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:.2in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;" align=center style='margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal'>3</p>
  </td>
  <td width=367 colspan=6 valign=top style='width:5.1in;border-top:none;
  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:.2in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;">Occupancy:<b> </b><b><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></b></p>
  </td>
 </tr>
 <tr style='height:.2in'>
  <td width=43 valign=top style='width:.6in;border-top:none;border-left:none;
  border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:.2in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;" align=center style='margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal'>4</p>
  </td>
  <td width=367 colspan=6 valign=top style='width:5.1in;border-top:none;
  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:.2in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;">Occupancy:<b> </b><b><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></b></p>
  </td>
 </tr>
 <tr style='height:.2in'>
  <td width=43 valign=top style='width:.6in;border-top:none;border-left:none;
  border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:.2in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;" align=center style='margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal'>5</p>
  </td>
  <td width=367 colspan=6 valign=top style='width:5.1in;border-top:none;
  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt;height:.2in'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;">Occupancy:<b> </b><b><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></b></p>
  </td>
 </tr>
 <tr height=0>
  <td width=140 style='border:none'></td>
  <td width=43 style='border:none'></td>
  <td width=122 style='border:none'></td>
  <td width=61 style='border:none'></td>
  <td width=21 style='border:none'></td>
  <td width=41 style='border:none'></td>
  <td width=54 style='border:none'></td>
  <td width=68 style='border:none'></td>
 </tr>
</table>

<p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;">&nbsp;</p>

<table class=MsoTableGrid border=1 cellspacing=0 cellpadding=0
 style='border-collapse:collapse;border:none'>
 <tr>
  <td width=551 valign=top style='width:7.65in;border:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;">NOTES:<b> </b><b><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></b></p>
  </td>
 </tr>
 <tr>
  <td width=551 valign=top style='width:7.65in;border:solid windowtext 1.0pt;
  border-top:none;padding:0in 5.4pt 0in 5.4pt'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></p>
  </td>
 </tr>
 <tr>
  <td width=551 valign=top style='width:7.65in;border:solid windowtext 1.0pt;
  border-top:none;padding:0in 5.4pt 0in 5.4pt'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></p>
  </td>
 </tr>
 <tr>
  <td width=551 valign=top style='width:7.65in;border:solid windowtext 1.0pt;
  border-top:none;padding:0in 5.4pt 0in 5.4pt'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></p>
  </td>
 </tr>
 <tr>
  <td width=551 valign=top style='width:7.65in;border:solid windowtext 1.0pt;
  border-top:none;padding:0in 5.4pt 0in 5.4pt'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></p>
  </td>
 </tr>
 <tr>
  <td width=551 valign=top style='width:7.65in;border:solid windowtext 1.0pt;
  border-top:none;padding:0in 5.4pt 0in 5.4pt'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></p>
  </td>
 </tr>
 <tr>
  <td width=551 valign=top style='width:7.65in;border:solid windowtext 1.0pt;
  border-top:none;padding:0in 5.4pt 0in 5.4pt'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></p>
  </td>
 </tr>
 <tr>
  <td width=551 valign=top style='width:7.65in;border:solid windowtext 1.0pt;
  border-top:none;padding:0in 5.4pt 0in 5.4pt'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></p>
  </td>
 </tr>
 <tr>
  <td width=551 valign=top style='width:7.65in;border:solid windowtext 1.0pt;
  border-top:none;padding:0in 5.4pt 0in 5.4pt'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></p>
  </td>
 </tr>
 <tr>
  <td width=551 valign=top style='width:7.65in;border:solid windowtext 1.0pt;
  border-top:none;padding:0in 5.4pt 0in 5.4pt'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></p>
  </td>
 </tr>
 <tr>
  <td width=551 valign=top style='width:7.65in;border:solid windowtext 1.0pt;
  border-top:none;padding:0in 5.4pt 0in 5.4pt'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></p>
  </td>
 </tr>
 <tr>
  <td width=551 valign=top style='width:7.65in;border:solid windowtext 1.0pt;
  border-top:none;padding:0in 5.4pt 0in 5.4pt'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></p>
  </td>
 </tr>
 <tr>
  <td width=551 valign=top style='width:7.65in;border:solid windowtext 1.0pt;
  border-top:none;padding:0in 5.4pt 0in 5.4pt'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></p>
  </td>
 </tr>
 <tr>
  <td width=551 valign=top style='width:7.65in;border:solid windowtext 1.0pt;
  border-top:none;padding:0in 5.4pt 0in 5.4pt'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></p>
  </td>
 </tr>
 <tr>
  <td width=551 valign=top style='width:7.65in;border:solid windowtext 1.0pt;
  border-top:none;padding:0in 5.4pt 0in 5.4pt'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></p>
  </td>
 </tr>
 <tr>
  <td width=551 valign=top style='width:7.65in;border:solid windowtext 1.0pt;
  border-top:none;padding:0in 5.4pt 0in 5.4pt'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></p>
  </td>
 </tr>
 <tr>
  <td width=551 valign=top style='width:7.65in;border:solid windowtext 1.0pt;
  border-top:none;padding:0in 5.4pt 0in 5.4pt'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></p>
  </td>
 </tr>
 <tr>
  <td width=551 valign=top style='width:7.65in;border:solid windowtext 1.0pt;
  border-top:none;padding:0in 5.4pt 0in 5.4pt'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></p>
  </td>
 </tr>
 <tr>
  <td width=551 valign=top style='width:7.65in;border:solid windowtext 1.0pt;
  border-top:none;padding:0in 5.4pt 0in 5.4pt'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></p>
  </td>
 </tr>
 <tr>
  <td width=551 valign=top style='width:7.65in;border:solid windowtext 1.0pt;
  border-top:none;padding:0in 5.4pt 0in 5.4pt'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></p>
  </td>
 </tr>
 <tr>
  <td width=551 valign=top style='width:7.65in;border:solid windowtext 1.0pt;
  border-top:none;padding:0in 5.4pt 0in 5.4pt'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></p>
  </td>
 </tr>
 <tr>
  <td width=551 valign=top style='width:7.65in;border:solid windowtext 1.0pt;
  border-top:none;padding:0in 5.4pt 0in 5.4pt'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></p>
  </td>
 </tr>
 <tr>
  <td width=551 valign=top style='width:7.65in;border:solid windowtext 1.0pt;
  border-top:none;padding:0in 5.4pt 0in 5.4pt'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></p>
  </td>
 </tr>
 <tr>
  <td width=551 valign=top style='width:7.65in;border:solid windowtext 1.0pt;
  border-top:none;padding:0in 5.4pt 0in 5.4pt'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></p>
  </td>
 </tr>
 <tr>
  <td width=551 valign=top style='width:7.65in;border:solid windowtext 1.0pt;
  border-top:none;padding:0in 5.4pt 0in 5.4pt'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></p>
  </td>
 </tr>
 <tr>
  <td width=551 valign=top style='width:7.65in;border:solid windowtext 1.0pt;
  border-top:none;padding:0in 5.4pt 0in 5.4pt'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></p>
  </td>
 </tr>
 <tr>
  <td width=551 valign=top style='width:7.65in;border:solid windowtext 1.0pt;
  border-top:none;padding:0in 5.4pt 0in 5.4pt'>
  <p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></p>
  </td>
 </tr>
</table>

<p style="margin-top:0in;margin-right:0in;margin-bottom:10.0pt;margin-left:0in;line-height:115%;font-size:11.0pt;font-family:Calibri;"><span style='font-family:Arial;background:transparent'>&nbsp;</span></p>
  
</div>
</body>

</html>
